# https://github.com/wg/wrk
#  Usage: wrk <options> <url>                            
#  Options:                                            
#    -c, --connections <N>  Connections to keep open   
#    -d, --duration    <T>  Duration of test           
#    -t, --threads     <N>  Number of threads to use   
#                                                      
#    -s, --script      <S>  Load Lua script file       
#    -H, --header      <H>  Add header to request      
#        --latency          Print latency statistics   
#        --timeout     <T>  Socket/request timeout     
#    -v, --version          Print version details      
#                                                      
#  Numeric arguments may include a SI unit (1k, 1M, 1G)
#  Time arguments may include a time unit (2s, 2m, 2h)
# https://www.nginx.com/blog/nginx-plus-sizing-guide-how-we-tested/
# If you want run in your laptop:
# docker run --rm williamyeh/wrk -t1 -c1000 -d5m --latency --timeout 30s "https://www.stg.HOST.com/en/"
apiVersion: batch/v1
kind: CronJob
metadata:
  name: wrk-rps-performance-cronjob
  namespace: web
spec:
  schedule: "0 0 1 1 *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: wrk-rps-performance-cronjob
            image: williamyeh/wrk
            command:
            - wrk
            - "-t1"
            - "-c800"
            - "-d15m"
            - "--latency"            
            - "--timeout" 
            - "5s"
            - "https://URL"
          restartPolicy: Never        